name: Docker Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker buildx build --push --build-arg SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) --platform linux/amd64,linux/arm64 --iidfile /tmp/iid --tag ghcr.io/wiktor-k/paperboy --output "type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/wiktor-k/paperboy,annotation-index.org.opencontainers.image.description=Simple backend that retrieves newspaper PDFs from an online service,annotation-index.org.opencontainers.image.licenses=Apache-2.0" .
      - name: Print image ID
        run: cat /tmp/iid
